### ISSUE TITLE
Change donate link to HCB

### ISSUE THREAD

**Issue by GovInTrenches** [civictechnologists/website#18]
The donate link should now point to: https://hcb.hackclub.com/donations/start/alliance-of-civic-technologists

**Comment by devendra0009** [comment]
Hi, 
Can u clear the doubt the existing Donate button is currently pointing to ( https://opencollective.com/act-fund ) this link. 
And now it is should point to ( https://hcb.hackclub.com/donations/start/alliance-of-civic-technologists )
Can you approve if it is the same blue button that is on the navbar? Where all do you want to add this link to ? There is one more red donate button.
