### ISSUE TITLE
Redirect Footer Discord Link

### ISSUE THREAD

**Issue by createHernandez** [civictechnologists/website#22]
Currently the Discord link in the footer is linking back to the [home page](https://www.civictechnologists.org/). It needs to be changed to link to the [permanent Discord server invite](https://discord.com/invite/EM6ywtMhkP).

**Comment by bensheldon** [comment]
Whoops! I can fix that real quick. Thanks!

**Comment by bensheldon** [comment]
I just pushed the fix and it should publish in about 5 minutes. Thank you again!
