### ISSUE TITLE
Place buttons on home page for interest and application form 

### ISSUE THREAD

**Issue by GovInTrenches** [civictechnologists/website#27]
The homepage should have our membership application and interest form right up front. 

Title: Membership Applications Now Open

Membership applications for existing local civic tech organizations is now open! Click HERE to apply! (Membership form https://docs.google.com/forms/d/e/1FAIpQLSe1Y4ht-9W-tXDMvnugLCHbs81YWP9N4AR1oPdtWpkAW98ZfQ/viewform?usp=sf_link) 

At this time, ACT is not accepting applications from new local civic tech organizations but you can express interest HERE! 
(https://docs.google.com/forms/d/e/1FAIpQLSdrrgzKSE21gWHR2zQChgEk_0qeaRoGmMqigg7bDkSOLgNLLQ/viewform?usp=sf_link)

**Comment by bensheldon** [comment]
Closed by #31
