### ISSUE TITLE
Move calls to action above the fold

### ISSUE THREAD

**Issue by krusynth** [civictechnologists/website#6]
I'd strongly recommend moving the two call-to-action buttons from the bottom of the homepage to the top. 

Also, add those as links in the header on the other content pages, with clear differentiation to draw the eye.

**Comment by bensheldon** [comment]
From discussion in Discord, two calls to action:

- Donate
- Join:
  - Subscribe to the newsletter
  - Join the discord
  - (tbd) Become a member org
